# Generated by Django 2.2 on 2021-06-04 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreU', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fichero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreF', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('modo', models.CharField(max_length=50)),
                ('fichero', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Fichero')),
                ('usuario', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Usuario')),
            ],
        ),
    ]
